apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp
  labels:
    app: vproapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: vprocontainers/vprofileapp
        ports:
        - containerPort: 8080
          name: vproapp-port

      initContainers:
      - name: init-wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 vprodb 3306; do echo "Waiting for database..."; sleep 5; done;']
      - name: init-wait-for-rmq
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 vpromq01 5672; do echo "Waiting for RabbitMQ..."; sleep 5; done;']
      - name: init-wait-for-mc
        image: busybox
        command: ['sh', '-c', 'until nc -z -v -w30 vprocache01 11211; do echo "Waiting for Memcached..."; sleep 5; done;']    